### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xiaomsky** [wistbean/learn_python3_spider#52]
有没有遇到下面这个错误的，求指教个方向：
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /?cdn=nohost (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f46c5bba8>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by newbie-hue** [comment]
代理没用对
，调整request

---Original---
From: ***@***.***&gt;
Date: Tue, Feb 22, 2022 09:00 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [wistbean/learn_python3_spider] error (Issue #52)




 
有没有遇到下面这个错误的，求指教个方向：
 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /?cdn=nohost (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f46c5bba8&gt;: Failed to establish a new connection: [Errno 111] Connection refused',))
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaomsky** [comment]
> 代理没用对 ，调整request
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Tue, Feb 22, 2022 09:00 AM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [wistbean/learn_python3_spider] error (Issue #52) 有没有遇到下面这个错误的，求指教个方向： urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /?cdn=nohost (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f46c5bba8&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)) — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

没有设置代理，这个是京东抢购的脚本，貌似是现在京东都改成手机app端抢的，PC页面可能没法用了

**Comment by wistbean** [comment]
import requests
from lxml import html

page = requests.get("https://itunes.apple.com/in/genre/ios-business/id6000?mt=8")
tree = html.fromstring(page.text)

flist = []
plist = []
for i in range(0, 100):
    app = tree.xpath("//div[@class='column first']/ul/li/a/@href")
    ap = app[0]
    page1 = requests.get(ap)


更多参考：https://stackoverflow.com/questions/23013220/max-retries-exceeded-with-url-in-requests
